# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Naturaily
email: hello@naturaily.com
description: > # this means to ignore newlines until "baseurl:"
  Agile web and mobile development team building Ruby on Rails, React and
  React Native applications for startups and enterprises. Let’s talk!
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://naturaily.com' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: naturaily
github_username:  naturaily
highlighter: rouge
pagination:
  enabled: true
  per_page: 5
  permalink: '/:num/'
  indexpage: 'index'
  sort_reverse: true
collections:
  career:
    output: true
    permalink: /join/:path
  portfolio:
    output: true
    permalink: /portfolio/:path
  project:
    output: true
    permalink: /project/:path
  services:
    output: true
    permalink: /services/index.html
  authors:
    output: true
    permalink: blog/authors/:path
  test:
    output: true

blog:
  tags:
    url: /blog/tags/
    title_prefix: " "
    layout: tag.html
  categories:
    url: /blog/categories/
    title_prefix: " "
    layout: category.html
  authors:
    url: /blog/authors/
    title_prefix: " "
    layout: author.html


defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      comments: true
      description: ' '
      category: ' '
      author: ' '
      tags: ' '
      image: ' '
      text-preview: ' '
  -
    scope:
      path: ''
      type: 'career'
    values:
      layout: 'career-details'
      published: ''
      description: ' '
      type: ' '
      salary: ' '
      requirements: '   '
      responsibilities: '   '
      offer: '   '
      benefits: '   '
      salary-range: '   '
  -
    scope:
      path: ''
      type: 'services'
    values:
      layout: 'services'

permalink: /blog/:title

pwa:
  sw_src_filepath: service-worker.js # Optional
  sw_dest_filename: service-worker.js # Optional
  dest_js_directory: assets/js # Required
  cache_name: my-cache # Optional
  precache_recent_posts_num: 5 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
    - index.html
  precache_glob_ignores: # Optional
    - sw-register.js
    - "fonts/**/*"

compress_images:
  images_path: "assets/images/**/*.{gif,png,jpg,jpeg,svg}"

imageoptim:
  skip_missing_workers: true
  nice: 5
  threads: 4
  svgo: false

jekyll-minifier:
  uglifier_args:
    harmony: true

# Build settings

sass:
  sass_dir: _sass
  style: compressed

markdown: kramdown
kramdown:
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-debug
  - jekyll-include-cache
  - jekyll-pwa-plugin
  - jekyll-compress-images
  - jekyll-minifier

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _compress_images_cache.yml

include:
  - .htaccess
  - node_modules/uglifier/index.js
  - _redirects

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
