# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Naturaily
email: hello@naturaily.com
description: > # this means to ignore newlines until "baseurl:"
  Agile web and mobile development team building Ruby on Rails, React and
  React Native applications for startups and enterprises. Let’s talk!
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://naturaily.com' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: naturaily
github_username:  naturaily
highlighter: rouge
pagination:
  enabled: true
  per_page: 5
  permalink: '/:num/'
  indexpage: 'index'
  sort_reverse: true
collections:
  career:
    output: true
    permalink: /join/:path
  portfolio:
    output: true
    permalink: /project/:path
  services:
    output: true
    permalink: /services/index.html
  authors:
    output: true
    permalink: blog/authors/:path
  test:
    output: true

blog:
  tags:
    url: /blog/tags/
    title_prefix: " "
    layout: tag.html
  categories:
    url: /blog/categories/
    title_prefix: " "
    layout: category.html
  authors:
    url: /blog/authors/
    title_prefix: " "
    layout: author.html


defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      comments: true
      description: ' '
      category: ' '
      author: ' '
      tags: ' '
      image: ' '
      text-preview: ' '
  -
    scope:
      path: ''
      type: 'career'
    values:
      layout: 'career-details'
      published: ''
      description: ' '
      type: ' '
      salary: ' '
      requirements: '   '
      responsibilities: '   '
      offer: '   '
      benefits: '   '
      salary-range: '   '
  -
    scope:
      path: ''
      type: 'services'
    values:
      layout: 'services'

include:
  - _redirects

permalink: /blog/:title

# Build settings

assets:
  source_maps: true # false on JEKYLL_ENV=production
  destination: "/assets"
  compression: true # true on JEKYLL_ENV=production
  gzip: true
  defaults:
    js: { integrity: true } # true on JEKYLL_ENV=production
    css: { integrity: true } # true on JEKYLL_ENV=production
    img: { integrity: true } # true on JEKYLL_ENV=production
  caching:
    path: ".jekyll-cache/assets"
    type: file # Possible values: memory, file
    enabled: true
  # --
  # Assets you wish to always have compiled.
  #   This can also be combined with raw_precompile which
  #   copies assets without running through the pipeline
  #   making them ultra fast.
  # --
  precompile: []
  raw_precompile: [
    #
  ]
  # --
  # baseurl: whether or not to append site.baseurl
  # destination: the folder you store them in on the CDN.
  # url: the CDN url (fqdn, or w/ identifier).
  # --
  cdn:
    baseurl: false
    destination: false
    url: null
  # --
  # These are all default. No need to add them
  #   Only use this if you have more.
  # --
  sources:
    - assets/css
    - assets/fonts
    - assets/images
    - assets/videos
    - assets/javascript
    - assets/video
    - assets/image
    - assets/img
    - assets/js
    - _assets/css
    - _assets/fonts
    - _assets/images
    - _assets/videos
    - _assets/javascript
    - _assets/video
    - _assets/image
    - _assets/img
    - _assets/js
    - css
    - fonts
    - images
    - videos
    - javascript
    - video
    - image
    - img
    - js
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}

markdown: kramdown
kramdown:
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-assets

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.txt
  - README.md
