version: "3"

services:
  web:
    build: .
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
    volumes:
      - .:/app
      - bundle:/bundle
    command: bundle exec jekyll serve --host 0.0.0.0

volumes:
  bundle:
