backend:
  name: git-gateway
  branch: develop

publish_mode: editorial_workflow

media_folder: "assets/images"

collections:
  -
    name: "post"
    label: "Posts"
    label_singular: "Post"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Date posted", name: "date", format: "YYYY-MM-DD hh:mm:ss +0000", widget: "date"}
      - {label: "Author name", name: "author", widget: "string"}
      - {label: "Author avatar", name: "avatar", widget: "image"}
      - {label: "Post image", name: "image", widget: "image"}
      - {label: "Post preview", name: "text-preview", widget: "text"}
      - label: "Tags"
        name: "tags"
        widget: "list"
        allow_add: true
      - {label: "Body", name: "body", widget: "markdown"}
  -
    name: "career"
    label: "Job offers"
    label_singular: "Job offer"
    folder: "_career"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "career-details"}
      - label: "Offer type"
        name: "type"
        widget: "select"
        options: ["programming", "design", "other"]
      - {label: "Salary", name: "salary", widget: "number", valueType: "string", min: 1}
      - label: "Responsibilities"
        name: "responsibilities"
        widget: "list"
        allow_add: true
        required: false
      - label: "Requirements"
        name: "requirements"
        widget: "list"
        allow_add: true
        required: false
      - label: "Nicehave"
        name: "nicehave"
        widget: "list"
        allow_add: true
        required: false
      - label: "Offer"
        name: "offer"
        widget: "list"
        allow_add: true
        required: false
      - label: "Salary range"
        name: "salary-range"
        widget: "list"
        allow_add: true
        required: false
