backend:
  name: git-gateway
  branch: develop

publish_mode: editorial_workflow

media_folder: "assets/images"

collections:
  -
    name: "post"
    label: "Posts"
    label_singular: "Post"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Date posted", name: "date", format: "YYYY-MM-DD hh:mm:ss +0000", widget: "date"}
      - {label: "Category", name: "category", widget: "text"}
      - {label: "Author name", name: "author", widget: "string"}
      - {label: "Author avatar", name: "avatar", widget: "image"}
      - {label: "Post image", name: "image", widget: "image"}
      - {label: "Post preview", name: "text-preview", widget: "text"}
      - label: "Tags"
        name: "tags"
        widget: "list"
        allow_add: true
      - {label: "Body", name: "body", widget: "markdown"}
  -
    name: "career"
    label: "Job offers"
    label_singular: "Job offer"
    folder: "_career"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "career-details"}
      - label: "Offer type"
        name: "type"
        widget: "select"
        options: ["programming", "design", "other"]
      - {label: "Salary", name: "salary", widget: "number", valueType: "string", min: 1}
      - label: "Responsibilities"
        name: "responsibilities"
        widget: "list"
        allow_add: true
        required: false
      - label: "Requirements"
        name: "requirements"
        widget: "list"
        allow_add: true
        required: false
      - label: "Nicehave"
        name: "nicehave"
        widget: "list"
        allow_add: true
        required: false
      - label: "Offer"
        name: "offer"
        widget: "list"
        allow_add: true
        required: false
      - label: "Salary range"
        name: "salary-range"
        widget: "list"
        allow_add: true
        required: false
  -
    name: "portfolio"
    label: "Portfolio"
    folder: "_portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "portfolio-details"}
      - {label: "Project font", name: "project-font", widget: "string", required: false}
      - {label: "Project screen", name: "project-screen", widget: "image"}
      - {label: "Project logo", name: "project-logo", widget: "image"}
      - {label: "Project logo class", name: "project-logo-class", widget: "string", required: false}
      - {label: "Banner background image", name: "banner-bg", widget: "image"}
      - {label: "Banner text", name: "banner-text", widget: "string"}
      - {label: "Banner tech", name: "banner-tech", widget: "list", allow_add: true}
      - {label: "Step one heading", name: "step-one", widget: "string"}
      - {label: "Step one title", name: "step-one-title", widget: "string"}
      - {label: "Step one text", name: "step-one-text", widget: "string"}
      - {label: "Step two heading", name: "step-two", widget: "string"}
      - {label: "Step two title", name: "step-two-title", widget: "string"}
      - {label: "Step two text", name: "step-two-text", widget: "string"}
      - {label: "Step three heading", name: "step-three", widget: "string"}
      - {label: "Step three title", name: "step-three-title", widget: "string"}
      - {label: "Step three text", name: "step-three-text", widget: "string"}
      - {label: "Stack first tech", name: "src-stack-1", widget: "image"}
      - {label: "Stack alt first tech", name: "alt-stack-1", widget: "string"}
      - {label: "Stack first tech", name: "src-stack-2", widget: "image"}
      - {label: "Stack alt first tech", name: "alt-stack-2", widget: "string"}
      - {label: "Stack first tech", name: "src-stack-3", widget: "image"}
      - {label: "Stack alt first tech", name: "alt-stack-3", widget: "string"}
      - {label: "Step four heading", name: "step-four", widget: "string"}
      - {label: "Step four title", name: "step-four-title", widget: "string"}
      - {label: "Step four text", name: "step-four-text", widget: "string"}
      - {label: "Commen photo", name: "comment-photo", widget: "image"}
      - {label: "Comment name", name: "comment-name", widget: "string"}
      - {label: "Comment brand", name: "comment-brand", widget: "string"}
      - {label: "Comment logo", name: "comment-logo", widget: "image"}
      - {label: "Comment text", name: "comment-text", widget: "string"}
      - {label: "Slide left", name: "slide-left", widget: "string"}
      - {label: "Slide left logo", name: "slide-left-logo", widget: "image"}
      - {label: "Slide left link", name: "slide-left-link", widget: "string", default: "/project/project_name"}
      - {label: "Slide right", name: "slide-right", widget: "string"}
      - {label: "Slide right logo", name: "slide-right-logo", widget: "image"}
      - {label: "Slide right link", name: "slide-right-link", widget: "string", default: "/project/project_name"}
      - {label: "Image one", name: "image-one", widget: "image"}
      - {label: "Image two", name: "image-two", widget: "image"}
      - {label: "Image three", name: "image-three", widget: "image"}
      - {label: "Image four", name: "image-four", widget: "image"}
      - {label: "Image five", name: "image-five", widget: "image"}
      - {label: "Image six", name: "image-six", widget: "image"}
  -
    name: "technologie"
    label: "Technologies"
    label_singular: "Technology Landing"
    folder: "_tech"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "description", name: "description", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "tech"}
      - {label: "permalink", name: "permalink", widget: "string"}
      - {label: "heading", name: "heading", widget: "string"}
      - {label: "desc", name: "desc", widget: "string"}
      - {label: "tech-head", name: "tech-head", widget: "string"}
      - {label: "tech-desc-one", name: "tech-desc-one", widget: "string"}
      - {label: "tech-desc-two", name: "tech-desc-two", widget: "string"}
      - {label: "tech-logo-first", name: "tech-logo-first", widget: "image"}
      - {label: "tech-name-first", name: "tech-name-first", widget: "string"}
      - {label: "tech-logo-seconf", name: "tech-logo-seconf", widget: "image"}
      - {label: "tech-name-second", name: "tech-name-second", widget: "string"}
      - {label: "tech-logo-third", name: "tech-logo-third", widget: "image"}
      - {label: "tech-name-third", name: "tech-name-third", widget: "string"}
      - {label: "advantage-head", name: "advantage-head", widget: "string"}
      - {label: "advantage-subtitle", name: "advantage-subtitle", widget: "string"}
      - {label: "advantage-desc-one-title", name: "advantage-desc-one-title", widget: "string"}
      - {label: "advantage-desc-one", name: "advantage-desc-one", widget: "string"}
      - {label: "advantage-desc-two-title", name: "advantage-desc-two-title", widget: "string"}
      - {label: "advantage-desc-two", name: "advantage-desc-two", widget: "string"}
      - {label: "advantage-desc-three-title", name: "advantage-desc-three-title", widget: "string"}
      - {label: "advantage-desc-three", name: "advantage-desc-three", widget: "string"}
      - {label: "advantage-desc-four-title", name: "advantage-desc-four-title", widget: "string"}
      - {label: "advantage-desc-four", name: "advantage-desc-four", widget: "string"}
      - {label: "projects-slogan", name: "projects-slogan", widget: "string"}
      - {label: "projects-head", name: "projects-head", widget: "string"}
      - label: "Projects"
        name: "projects"
        widget: "list"
        allow_add: true
        fields:
          - label: Project
            name: project
            widget: object
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Desc", name: "desc", widget: "string"}
              - {label: "Image", name: "bg", widget: "image"}
              - {label: "Background Image", name: "bg-image", widget: "image"}
      - {label: "blog-head", name: "blog-head", widget: "string"}
      - {label: "blog-desc", name: "blog-desc", widget: "string"}
      - label: "competences"
        name: "competences"
        widget: "list"
        allow_add: true
        fields:
          - {label: "tech-name", name: "tech-name", widget: "string"}
      - {label: "competences-text", name: "competences-text", widget: "string"}
